replicaCount: 1

image:
  repository: localhost:5001/gateway-service
  tag: "0.0.1"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 3000

config:
  nodeEnv: production
  port: "3000"
  grpcIdentityUrl: identity-service.microservices.svc.cluster.local:50051
  natsServers: nats://nats.infra.svc.cluster.local:4222

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: false
  minAvailable: 1

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
